# Partial backend configuration: the bucket name is supplied at init time from
# backend.hcl (git-ignored), generated by `make backend-config`.
terraform {
  backend "s3" {
    key            = "env/staging/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "iac-terraform-locks"
  }
}
